plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.galgame'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.galgame"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug   // 测试签名（我们不上架，够用）
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
